### ISSUE TITLE
Please add license terms

### ISSUE THREAD

**Issue by roptat** [rgrinberg/stringext#8]
Hi,

The only mention of a license in this repository is in the opam file, where you specify the license is "MIT". Since this name can be used for at least two distinct license terms (although very close), please add a LICENSE or COPYING file with the exact terms you mean by that. I suppose you mean https://directory.fsf.org/wiki/License:Expat, but it could also be https://directory.fsf.org/wiki/License:X11 or a variant thereof.

It would be best to add a license and copyright statement at the beginning of all your source files, but I will already be very happy with only a LICENSE file.

Thank you :)

**Comment by rgrinberg** [comment]
OK I've added a LICENSE file. I chose the Expat terms with the 1 difference of adding the license name to the top of the file. Makes it easier to identify the license for people who aren't as familiar with this stuff.

Will slowly start adding the copyright statement to every source file eventually..

**Comment by roptat** [comment]
Thanks a lot, that was quick!
